### ISSUE TITLE
Cancel "Waiting for Review"

### ISSUE THREAD

**Issue by pedro380085** [fastlane/itc-api-docs#10]
Hi @KrauseFx ,

I know that is not your problem, but can you help me to remove an app from review? (http://stackoverflow.com/questions/32959058/ios-9-cant-remove-build-from-review-in-itunesconnect) This option is disabled on the new iTC panel and I can't find a way to get it working with Apple Support.

I've tried using `https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/version/reject/[app_id]` but it is marked as deprecated. Do you new what would be the new path?

Thank you very much!

**Comment by KrauseFx** [comment]
I recommend contact the Apple support instead of using undocumented API to do something like this. Is there a reason you don't contact Apple support?

You could also just add `Android` to all your descriptions and app titles so the update gets rejected :wink:

**Comment by pedro380085** [comment]
Hi Felix,

I have contacted them 12 times in the last two days, but they are
overwhelmed from itc bugs, I believe.

You don't know the updated path?

Thanks,

**Comment by KrauseFx** [comment]
Sorry, no.

**Comment by pedro380085** [comment]
ok, thanks anyway!

**Comment by pedro380085** [comment]
Hi @KrauseFx ,

Just wanted to share that I found it out :) (for those in need).

`https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/[app_id]/versions/[version_id]/reject`

**Comment by KrauseFx** [comment]
Yeah :+1: Feel free to submit a pull request with the updated URL.

**Comment by stianjensen** [comment]
This URL doesn't seem to work anymore.

**Comment by KrauseFx** [comment]
This project is deprecated https://github.com/fastlane/itc-api-docs#project-status
