### ISSUE TITLE
App json urls now deprecated

### ISSUE THREAD

**Issue by pieisgood** [fastlane/itc-api-docs#12]
It seems that the list apps url and maybe others are now returning json stating that the it is deprecated. Just started happening for me.

**Comment by KrauseFx** [comment]
`deprecated`, so is the project: https://github.com/fastlane/itc-api-docs#project-status :+1:

**Comment by pieisgood** [comment]
Well, shit. A lot of work ahead then. Thanks, didn't notice this was deprecated. :+1: 

:rage1:

**Comment by KrauseFx** [comment]
From now on I'm focusing on [spaceship](https://spaceship.airforce) :rocket:
