### ISSUE TITLE
itc api 

### ISSUE THREAD

**Issue by jeffreyjackson** [fastlane/itc-api-docs#2]
Hey @KrauseFx, I'm working on a personal project and looking for some type of documentation on how to authenticate with ITC.  That's really all I need, just need some way to ensure my iOS app is authenticated on ITC so I can run other queries I have setup already to go.  

Can you point me in the right direction?

**Comment by KrauseFx** [comment]
Sure thing @jeffreyjackson. Doesn't the login action (https://github.com/fastlane/itc-api-docs#login) help? 

What kind of queries do you want to send?

**Comment by jeffreyjackson** [comment]
I'm building a simple iOS app for looking at the review data for each app.  Unfortunately, you have to be authenticated to get this information.  Ideally, I'd like to build a small class that I can use to authenticate into iTC with, and manage the session.

**Comment by KrauseFx** [comment]
Uh, I'm not sure that's the right way to do so. The API documentation here is mostly about app modifications and not reviews. There are quite some open source libraries doing what you want to do. You could take a look there?

**Comment by jeffreyjackson** [comment]
Right, I understand - the only missing piece I need is to just auth with iTC

**Comment by KrauseFx** [comment]
Why don't you use the `login` action then? https://github.com/fastlane/itc-api-docs#login

**Comment by jeffreyjackson** [comment]
Thank you sir!  :beers: :grimacing:

**Comment by KrauseFx** [comment]
Glad I could help, have fun :smiley:
