### ISSUE TITLE
Paw example file is out-of-date (or corrupt?)

### ISSUE THREAD

**Issue by cbowns** [fastlane/itc-api-docs#20]
I tried using the example Paw file per [the docs](https://github.com/fastlane/itc-api-docs/#testingusing-the-api) but get an error from Paw 3.0.16:

<img width="532" alt="screenshot 2017-03-16 10 41 32" src="https://cloud.githubusercontent.com/assets/474/24010565/7fc804ae-0a35-11e7-8b89-c16fa557c9d9.png">

**Comment by KrauseFx** [comment]
Hey @cbowns, as described in https://github.com/fastlane/itc-api-docs#project-status this repo is not maintained any more, as we moved everything to [spaceship](https://spaceship.airforce) 👍

**Comment by cbowns** [comment]
👍
