### ISSUE TITLE
the pre-filled PAW file could not be opened.

### ISSUE THREAD

**Issue by Agenric** [fastlane/itc-api-docs#24]
I downloaded this file, but Paw can't open it. Who can help me.

![image](https://user-images.githubusercontent.com/11513056/29566519-b733f1ae-877c-11e7-8421-16791c9274df.png)

**Comment by ignazioc** [comment]
same here

**Comment by KrauseFx** [comment]
Duplicate of https://github.com/fastlane/itc-api-docs/issues/20
