### ISSUE TITLE
Paw file is corrupted 

### ISSUE THREAD

**Issue by Vkt0r** [fastlane/itc-api-docs#26]
@KrauseFx I'm trying to open the Paw file with the predefined values to reach the iTunes Connect API but I think the way in which was created the file is different now in Paw as they are encrypting the Paw files I think because I can open your file and see the XML but not for the new ones.

Can you mind please submit a new one updated if you have it?? Thanks

**Comment by KrauseFx** [comment]
Duplicate of https://github.com/fastlane/itc-api-docs/issues/24, sorry
