### ISSUE TITLE
App Rejection API's?

### ISSUE THREAD

**Issue by pieisgood** [fastlane/itc-api-docs#5]
I haven't seen anything regarding app rejection here. If I want to check the reasons my app was rejected and handle these issues, without going into iTunes connect directly; I don't see a way currently.

**Comment by KrauseFx** [comment]
I don't think there is an API for that, as it's a HTML page which was not yet updated to the new AngularJS-based front-end. 

I don't have access to a reject app right now, so I can't take a closer look.

**Comment by pieisgood** [comment]
kick ass, thanks for updating the docs!

**Comment by KrauseFx** [comment]
@pieisgood Sorry, I forgot about updating this issue, but yes, the API is there. Also check out https://github.com/fastlane/spaceship/pull/58 in particular https://github.com/fastlane/spaceship/commit/4832041db337a7ac7fe6cb60e8a07fbdc02385cc
